version: '3.9'

services:
  postgres:
    image: postgres:16.1-alpine
    ports:
      - "54321:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: ["sh", "-c", "./manage.py migrate &&
             ./manage.py runserver 0.0.0.0:8000"]
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg-data:
